name: "Build .NetFramework"

on: 
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2 

      - uses: Restore Packages Nuget
        run: nuget restore ConsoleApp.sln
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Solution
        run: |    
            msbuild.exe ConsoleApp.sln /p:platform="Any CPU" /p:configuration="Release"

       