name: "Build .NetFramework"

on: 
  push:
    branches: 
      - dev
      - master
      - beta
  pull_request:
    branches:
      - dev
      - master
      - beta

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build Solution
        run: |    
            msbuild.exe ConsoleApp.sln /p:platform="Any CPU" /p:configuration="Release"

       